# Generated by Django 3.2.5 on 2021-12-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='midddle_name',
            new_name='middle_name',
        ),
    ]
