# Generated by Django 3.2.5 on 2021-12-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_midddle_name_personal_middle_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal',
            new_name='PersonalModel',
        ),
    ]
