# Generated by Django 3.2.9 on 2021-12-17 08:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in +977 format.', regex='^\\+?1?\\d{9,15}$')])),
                ('current_address', models.CharField(blank=True, max_length=50)),
                ('permanent_address', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'user',
            },
        ),
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name_plural': 'connection'},
        ),
        migrations.AlterField(
            model_name='connection',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
    ]
