# Generated by Django 4.0 on 2021-12-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed',
            field=models.BooleanField(default=False),
        ),
    ]
