export const mock = {
  form: [
    {
      heading: "Personal Detail",
      fields: [
        {
          name: "Name",
          label: "Name",
          field: "input",
          isrequired: "true",
          isRiskIndicator: false,
          values: [],
          riskLevel: "",
          riskIf: "",
        },
        {
          name: "Email",
          label: "Email",
          field: "input",
          isrequired: "true",
          isRiskIndicator: false,
          values: [],
          riskLevel: "",
          riskIf: "",
        },
        {
          name: "Age",
          label: "Age",
          field: "number",
          isrequired: "true",
          isRiskIndicator: false,
          values: [],
          riskLevel: "",
          riskIf: "",
        },
        {
          name: "Gender",
          label: "Gender",
          field: "dropdown",
          isrequired: "true",
          values: ["Male", "Female", "Other"],
          isRiskIndicator: false,
          riskLevel: "",
          riskIf: "",
        },
      ],
    },
    {
      heading: "Location",
      fields: [
        {
          name: "Country",
          label: "Country",
          field: "input",
          isrequired: "true",
          isRiskIndicator: false,
          values: [],
          riskLevel: "",
          riskIf: "",
        },
        {
          name: "State",
          label: "State",
          field: "input",
          isrequired: "true",
          isRiskIndicator: false,
          values: [],
          riskLevel: "",
          riskIf: "",
        },
        {
          name: "City",
          label: "City",
          field: "input",
          isrequired: "true",
          isRiskIndicator: false,
          values: [],
          riskLevel: "",
          riskIf: "",
        },
      ],
    },
    {
      heading: "Flood Risk Assessment",
      fields: [
        {
          name: "Have you experienced one or more flooding event in your life? ",
          label: "Have you experienced one or more flooding event in your life?",
          field: "dropdown",
          isrequired: "true",
          values: ["Yes", "No"],
          isRiskIndicator: true,
          riskLevel: "Moderate",
          riskIf: "Yes",
        },
      ],
    },
  ],
};
