# Generated by Django 4.0 on 2021-12-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='lower',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='upper',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
